### ISSUE TITLE
v0.1.0 Tracking Issue

### ISSUE THREAD

**Issue by BD103** [BD103/Claw#4]
- [x] #3
- [ ] New parsing system
    - [ ] Lexer
    - [ ] Parser
    - [ ] Update MSRV to 1.65.0
- [ ] Create intermediate representation for optimizations and easy transformation to schema
    - [ ] HIR
    - [ ] Query system
        - [ ] Optimizations setup
        - [ ] Error checking setup
- [ ] Make standard library
    - [ ] Macro for generating enum
    - [ ] Actually put in all the blocks
    - [ ] Shared types for enums, type system, etc.
- [ ] Convert schema to zip file in `claw_driver`
- [x] Website
    - [x] Book
    - [x] Rustdoc

## Optional

- [x] #6 
- [ ] Use [Clap](https://crates.io/crates/clap) for CLI argument parsing
- [ ] #10
- [ ] ~#12~
- [ ] READMEs filled out, example folder documented, `Cargo.toml` finalized
